### ISSUE TITLE
提问：这个客户端大约几分钟会刷新一次DNS？

### ISSUE THREAD

**Issue by Tellack** [zwh8800/cloudxns-ddns#1]
如题，我使用的是docker版客户端，想要了解下每隔多久会刷新一次DNS
以及公网IP是通过什么方式获取到的？
以及从docker客户端上如何查看DNS是否更新成功？
多谢了

**Comment by zwh8800** [comment]
1. 一分钟刷新一次
2. 公网IP通过调用cloudxns来获得的
3. 你可以直接去 https://www.cloudxns.net/Domain/index.html 这个网页里看对应的域名是否已经解析到IP。或者 https://www.cloudxns.net/AccountManage/userlog.html 这个页面也能看解析日志

**Comment by Tellack** [comment]
呃……我看了下你给的地址里的解析日志……似乎并没有发生更新……
我可以确定你的程序是正常运行在我的docker里的
我该如何debug呢？多谢了

**Comment by zwh8800** [comment]
有一个docker挂载点叫 `/app/log` 在这个里面会有日志可以看。你可以把 `/app/log/cloudxns-ddns.INFO` 贴过来

**Comment by Tellack** [comment]
啊……看出错误原因了……我以为它运行着，但实际上它根本就没运行。我把INFO附上来……
```
Log file created at: 2017/04/08 10:17:21
Running on machine: 4932d529b9f0
Binary: Built with gc go1.6.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0408 10:17:21.658684       1 conf.go:38] configuring...
F0408 10:17:21.659029       1 conf.go:41] error occored: open /app/config/cloudxns-ddns.gcfg: not a directory
goroutine 1 [running, locked to thread]:
github.com/golang/glog.stacks(0xc820022001, 0x0, 0x0, 0x0)
	/Users/zzz/go/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0x9c0a00, 0xc800000003, 0xc8201140c0, 0x9a1ca9, 0x7, 0x29, 0x0)
	/Users/zzz/go/src/github.com/golang/glog/glog.go:723 +0x31d
github.com/golang/glog.(*loggingT).printf(0x9c0a00, 0x3, 0x826580, 0x11, 0xc82002fed8, 0x1, 0x1)
	/Users/zzz/go/src/github.com/golang/glog/glog.go:655 +0x1d4
github.com/golang/glog.Fatalf(0x826580, 0x11, 0xc82002fed8, 0x1, 0x1)
	/Users/zzz/go/src/github.com/golang/glog/glog.go:1148 +0x5d
github.com/zwh8800/cloudxns-ddns/conf.init.1()
	/Users/zzz/go/src/github.com/zwh8800/cloudxns-ddns/conf/conf.go:41 +0x235
github.com/zwh8800/cloudxns-ddns/conf.init()
	/Users/zzz/go/src/github.com/zwh8800/cloudxns-ddns/conf/conf.go:44 +0x4f
github.com/zwh8800/cloudxns-ddns/cloudxns.init()
	/Users/zzz/go/src/github.com/zwh8800/cloudxns-ddns/cloudxns/url.go:5 +0x63
main.init()
	/Users/zzz/go/src/github.com/zwh8800/cloudxns-ddns/main.go:47 +0x59

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.2/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x9c0a00)
	/Users/zzz/go/src/github.com/golang/glog/glog.go:882 +0x67
created by github.com/golang/glog.init.1
	/Users/zzz/go/src/github.com/golang/glog/glog.go:410 +0x297
```

**Comment by zwh8800** [comment]
好像是 `/app/config/` 这个挂载点没有进行挂载。

你需要先创建一个文件夹，里面放一个文件叫做 `cloudxns-ddns.gcfg` ，编辑这个文件为以下内容。
```
[CloudXNS]
APIKey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
SecureKey="xxxxxxxxxxxxxx"

[Domain]
Data="home.lengzzz.com"
Data="haha.lengzzz.com"
```
然后把这个文件夹挂载到docker的 `/app/config/`

**Comment by Tellack** [comment]
现在问题来了……该怎样删除掉那个不工作的docker container……只要一run就报这个：
```
docker: Error response from daemon: Conflict. The container name "/cloudxns-ddns" is already in use by container 4932d529b9f02001dbbfd3a9181d8b45b8e0dee12f4d2e4bcb192e00f9417d68. You have to remove (or rename) that container to be able to reuse that name..
```

**Comment by zwh8800** [comment]
`docker rm -f /cloudxns-ddns`

**Comment by Tellack** [comment]
一次性成功，多谢指导了！

**Comment by Tellack** [comment]
话说我在本地日志里能看到DDNS在更新
```
Log file created at: 2017/04/09 10:26:31
Running on machine: 656dac12e686
Binary: Built with gc go1.6.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0409 10:26:31.664419       1 conf.go:38] configuring...
I0409 10:26:31.664831       1 main.go:35] server started
I0409 10:26:31.664837       1 main.go:17] ddns started
I0409 10:26:33.427074       1 main.go:28] ddns finished
I0409 10:27:31.325095       1 main.go:17] ddns started
I0409 10:27:31.941762       1 main.go:28] ddns finished
I0409 10:28:31.008017       1 main.go:17] ddns started
I0409 10:28:32.179991       1 main.go:28] ddns finished
I0409 10:29:31.000496       1 main.go:17] ddns started
I0409 10:29:31.868669       1 main.go:28] ddns finished
I0409 10:30:31.000480       1 main.go:17] ddns started
I0409 10:30:31.992531       1 main.go:28] ddns finished
I0409 10:31:31.000293       1 main.go:17] ddns started
I0409 10:31:31.643150       1 main.go:28] ddns finished
```
但是在CloudXNS的日志管理面板上，关于DNS的刷新动作一条也看不到，不过这应该没关系吧？

**Comment by Tellack** [comment]
完全没有刷新我的DNS……我把三份LOG都贴上来供您分析下
cloudxns-ddns.ERROR
```
Log file created at: 2017/04/09 10:40:32
Running on machine: 656dac12e686
Binary: Built with gc go1.6.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0409 10:40:32.043751       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: EOF
E0409 10:50:04.943430       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:51:01.226613       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:52:01.712309       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:53:01.602633       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:54:01.497824       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:55:02.993489       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:56:02.872355       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:57:02.067890       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:58:01.263463       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:59:02.534013       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:17:03.523211       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:18:01.578597       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:19:01.056704       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:20:01.075183       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:21:01.970672       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:22:01.934462       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:23:01.368249       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:24:02.018197       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:25:01.170487       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:26:01.148701       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:27:01.534246       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:29:32.316285       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: EOF
```
cloudxns-ddns.INFO
```
Log file created at: 2017/04/09 10:26:31
Running on machine: 656dac12e686
Binary: Built with gc go1.6.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0409 10:26:31.664419       1 conf.go:38] configuring...
I0409 10:26:31.664831       1 main.go:35] server started
I0409 10:26:31.664837       1 main.go:17] ddns started
I0409 10:26:33.427074       1 main.go:28] ddns finished
I0409 10:27:31.325095       1 main.go:17] ddns started
I0409 10:27:31.941762       1 main.go:28] ddns finished
I0409 10:28:31.008017       1 main.go:17] ddns started
I0409 10:28:32.179991       1 main.go:28] ddns finished
I0409 10:29:31.000496       1 main.go:17] ddns started
I0409 10:29:31.868669       1 main.go:28] ddns finished
I0409 10:30:31.000480       1 main.go:17] ddns started
I0409 10:30:31.992531       1 main.go:28] ddns finished
I0409 10:31:31.000293       1 main.go:17] ddns started
I0409 10:31:31.643150       1 main.go:28] ddns finished
I0409 10:32:31.083340       1 main.go:17] ddns started
I0409 10:32:32.103890       1 main.go:28] ddns finished
I0409 10:33:31.106804       1 main.go:17] ddns started
I0409 10:33:31.211367       1 main.go:28] ddns finished
I0409 10:34:31.619021       1 main.go:17] ddns started
I0409 10:34:33.273982       1 main.go:28] ddns finished
I0409 10:35:31.194145       1 main.go:17] ddns started
I0409 10:35:32.253745       1 main.go:28] ddns finished
I0409 10:36:31.556833       1 main.go:17] ddns started
I0409 10:36:32.653297       1 main.go:28] ddns finished
I0409 10:37:31.923618       1 main.go:17] ddns started
I0409 10:37:32.828409       1 main.go:28] ddns finished
I0409 10:38:31.456777       1 main.go:17] ddns started
I0409 10:38:32.827492       1 main.go:28] ddns finished
I0409 10:39:31.000318       1 main.go:17] ddns started
I0409 10:39:32.044779       1 main.go:28] ddns finished
I0409 10:40:32.035350       1 main.go:17] ddns started
E0409 10:40:32.043751       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: EOF
I0409 10:40:32.252148       1 main.go:28] ddns finished
I0409 10:41:31.208262       1 main.go:17] ddns started
I0409 10:41:32.708027       1 main.go:28] ddns finished
I0409 10:42:31.588196       1 main.go:17] ddns started
I0409 10:42:32.666447       1 main.go:28] ddns finished
I0409 10:43:31.200756       1 main.go:17] ddns started
I0409 10:43:32.188974       1 main.go:28] ddns finished
I0409 10:44:33.281101       1 main.go:17] ddns started
I0409 10:44:34.604512       1 main.go:28] ddns finished
I0409 10:45:31.268168       1 main.go:17] ddns started
I0409 10:45:32.598189       1 main.go:28] ddns finished
I0409 10:46:31.266530       1 main.go:17] ddns started
I0409 10:46:31.517050       1 main.go:28] ddns finished
I0409 10:47:31.189578       1 main.go:17] ddns started
I0409 10:47:32.107711       1 main.go:28] ddns finished
I0409 10:48:31.191363       1 main.go:17] ddns started
I0409 10:48:32.283025       1 main.go:28] ddns finished
I0409 10:49:31.231592       1 main.go:17] ddns started
E0409 10:50:04.943430       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:50:04.946182       1 main.go:28] ddns finished
I0409 10:50:31.224747       1 main.go:17] ddns started
E0409 10:51:01.226613       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:51:01.226650       1 main.go:28] ddns finished
I0409 10:51:31.588877       1 main.go:17] ddns started
E0409 10:52:01.712309       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:52:01.712382       1 main.go:28] ddns finished
I0409 10:52:31.602250       1 main.go:17] ddns started
E0409 10:53:01.602633       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:53:01.602707       1 main.go:28] ddns finished
I0409 10:53:31.000647       1 main.go:17] ddns started
E0409 10:54:01.497824       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:54:01.497890       1 main.go:28] ddns finished
I0409 10:54:32.991044       1 main.go:17] ddns started
E0409 10:55:02.993489       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:55:02.993530       1 main.go:28] ddns finished
I0409 10:55:32.708873       1 main.go:17] ddns started
E0409 10:56:02.872355       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:56:02.872394       1 main.go:28] ddns finished
I0409 10:56:31.041569       1 main.go:17] ddns started
E0409 10:57:02.067890       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:57:02.067956       1 main.go:28] ddns finished
I0409 10:57:31.000602       1 main.go:17] ddns started
E0409 10:58:01.263463       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:58:01.263509       1 main.go:28] ddns finished
I0409 10:58:31.602453       1 main.go:17] ddns started
E0409 10:59:02.534013       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 10:59:02.534072       1 main.go:28] ddns finished
I0409 10:59:32.675769       1 main.go:17] ddns started
I0409 10:59:34.904318       1 main.go:28] ddns finished
I0409 11:00:32.090751       1 main.go:17] ddns started
I0409 11:00:33.071436       1 main.go:28] ddns finished
I0409 11:01:31.968414       1 main.go:17] ddns started
I0409 11:01:32.078885       1 main.go:28] ddns finished
I0409 11:02:31.422650       1 main.go:17] ddns started
I0409 11:02:32.479275       1 main.go:28] ddns finished
I0409 11:03:31.846423       1 main.go:17] ddns started
I0409 11:03:32.876903       1 main.go:28] ddns finished
I0409 11:04:31.631351       1 main.go:17] ddns started
I0409 11:04:32.678169       1 main.go:28] ddns finished
I0409 11:05:31.478344       1 main.go:17] ddns started
I0409 11:05:32.695941       1 main.go:28] ddns finished
I0409 11:06:31.793306       1 main.go:17] ddns started
I0409 11:06:32.816435       1 main.go:28] ddns finished
I0409 11:07:31.000270       1 main.go:17] ddns started
I0409 11:07:33.028591       1 main.go:28] ddns finished
I0409 11:08:32.012390       1 main.go:17] ddns started
I0409 11:08:33.104177       1 main.go:28] ddns finished
I0409 11:09:31.889240       1 main.go:17] ddns started
I0409 11:09:32.925021       1 main.go:28] ddns finished
I0409 11:10:31.411006       1 main.go:17] ddns started
I0409 11:10:32.510963       1 main.go:28] ddns finished
I0409 11:11:31.434541       1 main.go:17] ddns started
I0409 11:11:31.678510       1 main.go:28] ddns finished
I0409 11:12:31.116594       1 main.go:17] ddns started
I0409 11:12:32.208831       1 main.go:28] ddns finished
I0409 11:13:31.530976       1 main.go:17] ddns started
I0409 11:13:32.617135       1 main.go:28] ddns finished
I0409 11:14:31.813817       1 main.go:17] ddns started
I0409 11:14:32.486351       1 main.go:28] ddns finished
I0409 11:15:31.135989       1 main.go:17] ddns started
I0409 11:15:32.167134       1 main.go:28] ddns finished
I0409 11:16:33.316322       1 main.go:17] ddns started
E0409 11:17:03.523211       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:17:03.524921       1 main.go:28] ddns finished
I0409 11:17:31.577975       1 main.go:17] ddns started
E0409 11:18:01.578597       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:18:01.656681       1 main.go:28] ddns finished
I0409 11:18:31.056245       1 main.go:17] ddns started
E0409 11:19:01.056704       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:19:01.056751       1 main.go:28] ddns finished
I0409 11:19:31.000301       1 main.go:17] ddns started
E0409 11:20:01.075183       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:20:01.075236       1 main.go:28] ddns finished
I0409 11:20:31.969124       1 main.go:17] ddns started
E0409 11:21:01.970672       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:21:01.970708       1 main.go:28] ddns finished
I0409 11:21:31.162553       1 main.go:17] ddns started
E0409 11:22:01.934462       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:22:02.227377       1 main.go:28] ddns finished
I0409 11:22:31.355977       1 main.go:17] ddns started
E0409 11:23:01.368249       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:23:01.368285       1 main.go:28] ddns finished
I0409 11:23:31.333494       1 main.go:17] ddns started
E0409 11:24:02.018197       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:24:02.403089       1 main.go:28] ddns finished
I0409 11:24:31.001353       1 main.go:17] ddns started
E0409 11:25:01.170487       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:25:01.170546       1 main.go:28] ddns finished
I0409 11:25:31.148279       1 main.go:17] ddns started
E0409 11:26:01.148701       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:26:01.148750       1 main.go:28] ddns finished
I0409 11:26:31.000402       1 main.go:17] ddns started
E0409 11:27:01.534246       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
I0409 11:27:01.783936       1 main.go:28] ddns finished
I0409 11:27:31.000392       1 main.go:17] ddns started
I0409 11:27:32.662350       1 main.go:28] ddns finished
I0409 11:28:31.400156       1 main.go:17] ddns started
I0409 11:28:32.317440       1 main.go:28] ddns finished
I0409 11:29:31.000277       1 main.go:17] ddns started
E0409 11:29:32.316285       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: EOF
I0409 11:29:32.600506       1 main.go:28] ddns finished
I0409 11:30:31.117818       1 main.go:17] ddns started
I0409 11:30:32.644962       1 main.go:28] ddns finished
I0409 11:31:31.000297       1 main.go:17] ddns started
I0409 11:31:32.074657       1 main.go:28] ddns finished
I0409 11:32:31.650487       1 main.go:17] ddns started
I0409 11:32:32.709265       1 main.go:28] ddns finished
I0409 11:33:31.232849       1 main.go:17] ddns started
I0409 11:33:32.236384       1 main.go:28] ddns finished
I0409 11:34:31.413867       1 main.go:17] ddns started
I0409 11:34:32.714701       1 main.go:28] ddns finished
I0409 11:35:31.225159       1 main.go:17] ddns started
I0409 11:35:32.241689       1 main.go:28] ddns finished
I0409 11:36:33.203643       1 main.go:17] ddns started
I0409 11:36:34.183709       1 main.go:28] ddns finished
I0409 11:37:32.420206       1 main.go:17] ddns started
I0409 11:37:32.676871       1 main.go:28] ddns finished
I0409 11:38:31.232673       1 main.go:17] ddns started
I0409 11:38:32.292991       1 main.go:28] ddns finished
I0409 11:39:31.000308       1 main.go:17] ddns started
I0409 11:39:31.142814       1 main.go:28] ddns finished
I0409 11:40:32.566504       1 main.go:17] ddns started
I0409 11:40:33.995896       1 main.go:28] ddns finished
```
cloudxns-ddns.WARNING
```
Log file created at: 2017/04/09 10:40:32
Running on machine: 656dac12e686
Binary: Built with gc go1.6.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0409 10:40:32.043751       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: EOF
E0409 10:50:04.943430       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:51:01.226613       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:52:01.712309       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:53:01.602633       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:54:01.497824       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:55:02.993489       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:56:02.872355       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:57:02.067890       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:58:01.263463       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 10:59:02.534013       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:17:03.523211       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:18:01.578597       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:19:01.056704       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:20:01.075183       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:21:01.970672       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:22:01.934462       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:23:01.368249       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:24:02.018197       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:25:01.170487       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:26:01.148701       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:27:01.534246       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: dial tcp 42.236.6.137:443: i/o timeout
E0409 11:29:32.316285       1 main.go:25] Post https://www.cloudxns.net/api2/ddns: EOF
```

**Comment by Tellack** [comment]
问题忽然自行解决了，不需要帮助了，多谢
